"""add_stripe_columns_to_order

Revision ID: c4422dc994b4
Revises: 8d25bf301e34
Create Date: 2026-03-28 16:54:04.539985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4422dc994b4'
down_revision: Union[str, None] = '8d25bf301e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_method', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'stripe_payment_intent_id')
    op.drop_column('orders', 'payment_method')
    # ### end Alembic commands ###
